// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asr_service.proto

#ifndef PROTOBUF_asr_5fservice_2eproto__INCLUDED
#define PROTOBUF_asr_5fservice_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace sarmata {
class AudioRequest;
class AudioRequestDefaultTypeInternal;
extern AudioRequestDefaultTypeInternal _AudioRequest_default_instance_;
class ConfigField;
class ConfigFieldDefaultTypeInternal;
extern ConfigFieldDefaultTypeInternal _ConfigField_default_instance_;
class DefineGrammarRequest;
class DefineGrammarRequestDefaultTypeInternal;
extern DefineGrammarRequestDefaultTypeInternal _DefineGrammarRequest_default_instance_;
class DefineGrammarResponse;
class DefineGrammarResponseDefaultTypeInternal;
extern DefineGrammarResponseDefaultTypeInternal _DefineGrammarResponse_default_instance_;
class InitialRecognizeRequest;
class InitialRecognizeRequestDefaultTypeInternal;
extern InitialRecognizeRequestDefaultTypeInternal _InitialRecognizeRequest_default_instance_;
class Phrase;
class PhraseDefaultTypeInternal;
extern PhraseDefaultTypeInternal _Phrase_default_instance_;
class Phrase_Word;
class Phrase_WordDefaultTypeInternal;
extern Phrase_WordDefaultTypeInternal _Phrase_Word_default_instance_;
class RecognizeRequest;
class RecognizeRequestDefaultTypeInternal;
extern RecognizeRequestDefaultTypeInternal _RecognizeRequest_default_instance_;
class RecognizeResponse;
class RecognizeResponseDefaultTypeInternal;
extern RecognizeResponseDefaultTypeInternal _RecognizeResponse_default_instance_;
}  // namespace sarmata

namespace sarmata {

namespace protobuf_asr_5fservice_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_asr_5fservice_2eproto

enum ResponseStatus {
  EMPTY = 0,
  SUCCESS = 1,
  PARTIAL_MATCH = 2,
  NO_MATCH = 3,
  NO_INPUT_TIMEOUT = 4,
  GRAMMAR_LOAD_FAILURE = 5,
  GRAMMAR_COMPILATION_FAILURE = 6,
  RECOGNIZER_ERROR = 7,
  TOO_MUCH_SPEECH_TIMEOUT = 8,
  CANCELLED = 9,
  START_OF_INPUT = 10,
  END_OF_AUDIO = 11,
  SEMANTICS_FAILURE = 12,
  ResponseStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ResponseStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ResponseStatus_IsValid(int value);
const ResponseStatus ResponseStatus_MIN = EMPTY;
const ResponseStatus ResponseStatus_MAX = SEMANTICS_FAILURE;
const int ResponseStatus_ARRAYSIZE = ResponseStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* ResponseStatus_descriptor();
inline const ::std::string& ResponseStatus_Name(ResponseStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    ResponseStatus_descriptor(), value);
}
inline bool ResponseStatus_Parse(
    const ::std::string& name, ResponseStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResponseStatus>(
    ResponseStatus_descriptor(), name, value);
}
// ===================================================================

class RecognizeRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sarmata.RecognizeRequest) */ {
 public:
  RecognizeRequest();
  virtual ~RecognizeRequest();

  RecognizeRequest(const RecognizeRequest& from);

  inline RecognizeRequest& operator=(const RecognizeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RecognizeRequest(RecognizeRequest&& from) noexcept
    : RecognizeRequest() {
    *this = ::std::move(from);
  }

  inline RecognizeRequest& operator=(RecognizeRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RecognizeRequest& default_instance();

  static inline const RecognizeRequest* internal_default_instance() {
    return reinterpret_cast<const RecognizeRequest*>(
               &_RecognizeRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RecognizeRequest* other);
  friend void swap(RecognizeRequest& a, RecognizeRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RecognizeRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  RecognizeRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RecognizeRequest& from);
  void MergeFrom(const RecognizeRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RecognizeRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .sarmata.InitialRecognizeRequest initial_request = 1;
  bool has_initial_request() const;
  void clear_initial_request();
  static const int kInitialRequestFieldNumber = 1;
  const ::sarmata::InitialRecognizeRequest& initial_request() const;
  ::sarmata::InitialRecognizeRequest* mutable_initial_request();
  ::sarmata::InitialRecognizeRequest* release_initial_request();
  void set_allocated_initial_request(::sarmata::InitialRecognizeRequest* initial_request);

  // .sarmata.AudioRequest audio_request = 2;
  bool has_audio_request() const;
  void clear_audio_request();
  static const int kAudioRequestFieldNumber = 2;
  const ::sarmata::AudioRequest& audio_request() const;
  ::sarmata::AudioRequest* mutable_audio_request();
  ::sarmata::AudioRequest* release_audio_request();
  void set_allocated_audio_request(::sarmata::AudioRequest* audio_request);

  // @@protoc_insertion_point(class_scope:sarmata.RecognizeRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::sarmata::InitialRecognizeRequest* initial_request_;
  ::sarmata::AudioRequest* audio_request_;
  mutable int _cached_size_;
  friend struct protobuf_asr_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConfigField : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sarmata.ConfigField) */ {
 public:
  ConfigField();
  virtual ~ConfigField();

  ConfigField(const ConfigField& from);

  inline ConfigField& operator=(const ConfigField& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConfigField(ConfigField&& from) noexcept
    : ConfigField() {
    *this = ::std::move(from);
  }

  inline ConfigField& operator=(ConfigField&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfigField& default_instance();

  static inline const ConfigField* internal_default_instance() {
    return reinterpret_cast<const ConfigField*>(
               &_ConfigField_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ConfigField* other);
  friend void swap(ConfigField& a, ConfigField& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConfigField* New() const PROTOBUF_FINAL { return New(NULL); }

  ConfigField* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConfigField& from);
  void MergeFrom(const ConfigField& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConfigField* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:sarmata.ConfigField)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable int _cached_size_;
  friend struct protobuf_asr_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InitialRecognizeRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sarmata.InitialRecognizeRequest) */ {
 public:
  InitialRecognizeRequest();
  virtual ~InitialRecognizeRequest();

  InitialRecognizeRequest(const InitialRecognizeRequest& from);

  inline InitialRecognizeRequest& operator=(const InitialRecognizeRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InitialRecognizeRequest(InitialRecognizeRequest&& from) noexcept
    : InitialRecognizeRequest() {
    *this = ::std::move(from);
  }

  inline InitialRecognizeRequest& operator=(InitialRecognizeRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InitialRecognizeRequest& default_instance();

  static inline const InitialRecognizeRequest* internal_default_instance() {
    return reinterpret_cast<const InitialRecognizeRequest*>(
               &_InitialRecognizeRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(InitialRecognizeRequest* other);
  friend void swap(InitialRecognizeRequest& a, InitialRecognizeRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InitialRecognizeRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  InitialRecognizeRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const InitialRecognizeRequest& from);
  void MergeFrom(const InitialRecognizeRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(InitialRecognizeRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .sarmata.ConfigField config = 1;
  int config_size() const;
  void clear_config();
  static const int kConfigFieldNumber = 1;
  const ::sarmata::ConfigField& config(int index) const;
  ::sarmata::ConfigField* mutable_config(int index);
  ::sarmata::ConfigField* add_config();
  ::google::protobuf::RepeatedPtrField< ::sarmata::ConfigField >*
      mutable_config();
  const ::google::protobuf::RepeatedPtrField< ::sarmata::ConfigField >&
      config() const;

  // string token = 2;
  void clear_token();
  static const int kTokenFieldNumber = 2;
  const ::std::string& token() const;
  void set_token(const ::std::string& value);
  #if LANG_CXX11
  void set_token(::std::string&& value);
  #endif
  void set_token(const char* value);
  void set_token(const char* value, size_t size);
  ::std::string* mutable_token();
  ::std::string* release_token();
  void set_allocated_token(::std::string* token);

  // @@protoc_insertion_point(class_scope:sarmata.InitialRecognizeRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::sarmata::ConfigField > config_;
  ::google::protobuf::internal::ArenaStringPtr token_;
  mutable int _cached_size_;
  friend struct protobuf_asr_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AudioRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sarmata.AudioRequest) */ {
 public:
  AudioRequest();
  virtual ~AudioRequest();

  AudioRequest(const AudioRequest& from);

  inline AudioRequest& operator=(const AudioRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AudioRequest(AudioRequest&& from) noexcept
    : AudioRequest() {
    *this = ::std::move(from);
  }

  inline AudioRequest& operator=(AudioRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AudioRequest& default_instance();

  static inline const AudioRequest* internal_default_instance() {
    return reinterpret_cast<const AudioRequest*>(
               &_AudioRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(AudioRequest* other);
  friend void swap(AudioRequest& a, AudioRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AudioRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  AudioRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AudioRequest& from);
  void MergeFrom(const AudioRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AudioRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes content = 1;
  void clear_content();
  static const int kContentFieldNumber = 1;
  const ::std::string& content() const;
  void set_content(const ::std::string& value);
  #if LANG_CXX11
  void set_content(::std::string&& value);
  #endif
  void set_content(const char* value);
  void set_content(const void* value, size_t size);
  ::std::string* mutable_content();
  ::std::string* release_content();
  void set_allocated_content(::std::string* content);

  // bool end_of_stream = 2;
  void clear_end_of_stream();
  static const int kEndOfStreamFieldNumber = 2;
  bool end_of_stream() const;
  void set_end_of_stream(bool value);

  // @@protoc_insertion_point(class_scope:sarmata.AudioRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr content_;
  bool end_of_stream_;
  mutable int _cached_size_;
  friend struct protobuf_asr_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DefineGrammarRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sarmata.DefineGrammarRequest) */ {
 public:
  DefineGrammarRequest();
  virtual ~DefineGrammarRequest();

  DefineGrammarRequest(const DefineGrammarRequest& from);

  inline DefineGrammarRequest& operator=(const DefineGrammarRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DefineGrammarRequest(DefineGrammarRequest&& from) noexcept
    : DefineGrammarRequest() {
    *this = ::std::move(from);
  }

  inline DefineGrammarRequest& operator=(DefineGrammarRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DefineGrammarRequest& default_instance();

  static inline const DefineGrammarRequest* internal_default_instance() {
    return reinterpret_cast<const DefineGrammarRequest*>(
               &_DefineGrammarRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(DefineGrammarRequest* other);
  friend void swap(DefineGrammarRequest& a, DefineGrammarRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DefineGrammarRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  DefineGrammarRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DefineGrammarRequest& from);
  void MergeFrom(const DefineGrammarRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DefineGrammarRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string token = 1;
  void clear_token();
  static const int kTokenFieldNumber = 1;
  const ::std::string& token() const;
  void set_token(const ::std::string& value);
  #if LANG_CXX11
  void set_token(::std::string&& value);
  #endif
  void set_token(const char* value);
  void set_token(const char* value, size_t size);
  ::std::string* mutable_token();
  ::std::string* release_token();
  void set_allocated_token(::std::string* token);

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string grammar = 3;
  void clear_grammar();
  static const int kGrammarFieldNumber = 3;
  const ::std::string& grammar() const;
  void set_grammar(const ::std::string& value);
  #if LANG_CXX11
  void set_grammar(::std::string&& value);
  #endif
  void set_grammar(const char* value);
  void set_grammar(const char* value, size_t size);
  ::std::string* mutable_grammar();
  ::std::string* release_grammar();
  void set_allocated_grammar(::std::string* grammar);

  // @@protoc_insertion_point(class_scope:sarmata.DefineGrammarRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr token_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr grammar_;
  mutable int _cached_size_;
  friend struct protobuf_asr_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DefineGrammarResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sarmata.DefineGrammarResponse) */ {
 public:
  DefineGrammarResponse();
  virtual ~DefineGrammarResponse();

  DefineGrammarResponse(const DefineGrammarResponse& from);

  inline DefineGrammarResponse& operator=(const DefineGrammarResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DefineGrammarResponse(DefineGrammarResponse&& from) noexcept
    : DefineGrammarResponse() {
    *this = ::std::move(from);
  }

  inline DefineGrammarResponse& operator=(DefineGrammarResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DefineGrammarResponse& default_instance();

  static inline const DefineGrammarResponse* internal_default_instance() {
    return reinterpret_cast<const DefineGrammarResponse*>(
               &_DefineGrammarResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(DefineGrammarResponse* other);
  friend void swap(DefineGrammarResponse& a, DefineGrammarResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DefineGrammarResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  DefineGrammarResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DefineGrammarResponse& from);
  void MergeFrom(const DefineGrammarResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DefineGrammarResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string error = 2;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // .sarmata.ResponseStatus status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::sarmata::ResponseStatus status() const;
  void set_status(::sarmata::ResponseStatus value);

  // bool ok = 3;
  void clear_ok();
  static const int kOkFieldNumber = 3;
  bool ok() const;
  void set_ok(bool value);

  // @@protoc_insertion_point(class_scope:sarmata.DefineGrammarResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  int status_;
  bool ok_;
  mutable int _cached_size_;
  friend struct protobuf_asr_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RecognizeResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sarmata.RecognizeResponse) */ {
 public:
  RecognizeResponse();
  virtual ~RecognizeResponse();

  RecognizeResponse(const RecognizeResponse& from);

  inline RecognizeResponse& operator=(const RecognizeResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RecognizeResponse(RecognizeResponse&& from) noexcept
    : RecognizeResponse() {
    *this = ::std::move(from);
  }

  inline RecognizeResponse& operator=(RecognizeResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RecognizeResponse& default_instance();

  static inline const RecognizeResponse* internal_default_instance() {
    return reinterpret_cast<const RecognizeResponse*>(
               &_RecognizeResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(RecognizeResponse* other);
  friend void swap(RecognizeResponse& a, RecognizeResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RecognizeResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  RecognizeResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RecognizeResponse& from);
  void MergeFrom(const RecognizeResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RecognizeResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .sarmata.Phrase results = 5;
  int results_size() const;
  void clear_results();
  static const int kResultsFieldNumber = 5;
  const ::sarmata::Phrase& results(int index) const;
  ::sarmata::Phrase* mutable_results(int index);
  ::sarmata::Phrase* add_results();
  ::google::protobuf::RepeatedPtrField< ::sarmata::Phrase >*
      mutable_results();
  const ::google::protobuf::RepeatedPtrField< ::sarmata::Phrase >&
      results() const;

  // string error = 2;
  void clear_error();
  static const int kErrorFieldNumber = 2;
  const ::std::string& error() const;
  void set_error(const ::std::string& value);
  #if LANG_CXX11
  void set_error(::std::string&& value);
  #endif
  void set_error(const char* value);
  void set_error(const char* value, size_t size);
  ::std::string* mutable_error();
  ::std::string* release_error();
  void set_allocated_error(::std::string* error);

  // string warning = 3;
  void clear_warning();
  static const int kWarningFieldNumber = 3;
  const ::std::string& warning() const;
  void set_warning(const ::std::string& value);
  #if LANG_CXX11
  void set_warning(::std::string&& value);
  #endif
  void set_warning(const char* value);
  void set_warning(const char* value, size_t size);
  ::std::string* mutable_warning();
  ::std::string* release_warning();
  void set_allocated_warning(::std::string* warning);

  // .sarmata.ResponseStatus status = 1;
  void clear_status();
  static const int kStatusFieldNumber = 1;
  ::sarmata::ResponseStatus status() const;
  void set_status(::sarmata::ResponseStatus value);

  // int32 event_time = 4;
  void clear_event_time();
  static const int kEventTimeFieldNumber = 4;
  ::google::protobuf::int32 event_time() const;
  void set_event_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:sarmata.RecognizeResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::sarmata::Phrase > results_;
  ::google::protobuf::internal::ArenaStringPtr error_;
  ::google::protobuf::internal::ArenaStringPtr warning_;
  int status_;
  ::google::protobuf::int32 event_time_;
  mutable int _cached_size_;
  friend struct protobuf_asr_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Phrase_Word : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sarmata.Phrase.Word) */ {
 public:
  Phrase_Word();
  virtual ~Phrase_Word();

  Phrase_Word(const Phrase_Word& from);

  inline Phrase_Word& operator=(const Phrase_Word& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Phrase_Word(Phrase_Word&& from) noexcept
    : Phrase_Word() {
    *this = ::std::move(from);
  }

  inline Phrase_Word& operator=(Phrase_Word&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Phrase_Word& default_instance();

  static inline const Phrase_Word* internal_default_instance() {
    return reinterpret_cast<const Phrase_Word*>(
               &_Phrase_Word_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(Phrase_Word* other);
  friend void swap(Phrase_Word& a, Phrase_Word& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Phrase_Word* New() const PROTOBUF_FINAL { return New(NULL); }

  Phrase_Word* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Phrase_Word& from);
  void MergeFrom(const Phrase_Word& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Phrase_Word* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string transcript = 1;
  void clear_transcript();
  static const int kTranscriptFieldNumber = 1;
  const ::std::string& transcript() const;
  void set_transcript(const ::std::string& value);
  #if LANG_CXX11
  void set_transcript(::std::string&& value);
  #endif
  void set_transcript(const char* value);
  void set_transcript(const char* value, size_t size);
  ::std::string* mutable_transcript();
  ::std::string* release_transcript();
  void set_allocated_transcript(::std::string* transcript);

  // double confidence = 2;
  void clear_confidence();
  static const int kConfidenceFieldNumber = 2;
  double confidence() const;
  void set_confidence(double value);

  // int32 start = 3;
  void clear_start();
  static const int kStartFieldNumber = 3;
  ::google::protobuf::int32 start() const;
  void set_start(::google::protobuf::int32 value);

  // int32 end = 4;
  void clear_end();
  static const int kEndFieldNumber = 4;
  ::google::protobuf::int32 end() const;
  void set_end(::google::protobuf::int32 value);

  // double logprob = 5;
  void clear_logprob();
  static const int kLogprobFieldNumber = 5;
  double logprob() const;
  void set_logprob(double value);

  // @@protoc_insertion_point(class_scope:sarmata.Phrase.Word)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr transcript_;
  double confidence_;
  ::google::protobuf::int32 start_;
  ::google::protobuf::int32 end_;
  double logprob_;
  mutable int _cached_size_;
  friend struct protobuf_asr_5fservice_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Phrase : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sarmata.Phrase) */ {
 public:
  Phrase();
  virtual ~Phrase();

  Phrase(const Phrase& from);

  inline Phrase& operator=(const Phrase& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Phrase(Phrase&& from) noexcept
    : Phrase() {
    *this = ::std::move(from);
  }

  inline Phrase& operator=(Phrase&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Phrase& default_instance();

  static inline const Phrase* internal_default_instance() {
    return reinterpret_cast<const Phrase*>(
               &_Phrase_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(Phrase* other);
  friend void swap(Phrase& a, Phrase& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Phrase* New() const PROTOBUF_FINAL { return New(NULL); }

  Phrase* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Phrase& from);
  void MergeFrom(const Phrase& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Phrase* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Phrase_Word Word;

  // accessors -------------------------------------------------------

  // repeated .sarmata.Phrase.Word words = 1;
  int words_size() const;
  void clear_words();
  static const int kWordsFieldNumber = 1;
  const ::sarmata::Phrase_Word& words(int index) const;
  ::sarmata::Phrase_Word* mutable_words(int index);
  ::sarmata::Phrase_Word* add_words();
  ::google::protobuf::RepeatedPtrField< ::sarmata::Phrase_Word >*
      mutable_words();
  const ::google::protobuf::RepeatedPtrField< ::sarmata::Phrase_Word >&
      words() const;

  // string semantic_interpretation = 4;
  void clear_semantic_interpretation();
  static const int kSemanticInterpretationFieldNumber = 4;
  const ::std::string& semantic_interpretation() const;
  void set_semantic_interpretation(const ::std::string& value);
  #if LANG_CXX11
  void set_semantic_interpretation(::std::string&& value);
  #endif
  void set_semantic_interpretation(const char* value);
  void set_semantic_interpretation(const char* value, size_t size);
  ::std::string* mutable_semantic_interpretation();
  ::std::string* release_semantic_interpretation();
  void set_allocated_semantic_interpretation(::std::string* semantic_interpretation);

  // double confidence = 2;
  void clear_confidence();
  static const int kConfidenceFieldNumber = 2;
  double confidence() const;
  void set_confidence(double value);

  // bool correct = 3;
  void clear_correct();
  static const int kCorrectFieldNumber = 3;
  bool correct() const;
  void set_correct(bool value);

  // @@protoc_insertion_point(class_scope:sarmata.Phrase)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::sarmata::Phrase_Word > words_;
  ::google::protobuf::internal::ArenaStringPtr semantic_interpretation_;
  double confidence_;
  bool correct_;
  mutable int _cached_size_;
  friend struct protobuf_asr_5fservice_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RecognizeRequest

// .sarmata.InitialRecognizeRequest initial_request = 1;
inline bool RecognizeRequest::has_initial_request() const {
  return this != internal_default_instance() && initial_request_ != NULL;
}
inline void RecognizeRequest::clear_initial_request() {
  if (GetArenaNoVirtual() == NULL && initial_request_ != NULL) delete initial_request_;
  initial_request_ = NULL;
}
inline const ::sarmata::InitialRecognizeRequest& RecognizeRequest::initial_request() const {
  const ::sarmata::InitialRecognizeRequest* p = initial_request_;
  // @@protoc_insertion_point(field_get:sarmata.RecognizeRequest.initial_request)
  return p != NULL ? *p : *reinterpret_cast<const ::sarmata::InitialRecognizeRequest*>(
      &::sarmata::_InitialRecognizeRequest_default_instance_);
}
inline ::sarmata::InitialRecognizeRequest* RecognizeRequest::mutable_initial_request() {
  
  if (initial_request_ == NULL) {
    initial_request_ = new ::sarmata::InitialRecognizeRequest;
  }
  // @@protoc_insertion_point(field_mutable:sarmata.RecognizeRequest.initial_request)
  return initial_request_;
}
inline ::sarmata::InitialRecognizeRequest* RecognizeRequest::release_initial_request() {
  // @@protoc_insertion_point(field_release:sarmata.RecognizeRequest.initial_request)
  
  ::sarmata::InitialRecognizeRequest* temp = initial_request_;
  initial_request_ = NULL;
  return temp;
}
inline void RecognizeRequest::set_allocated_initial_request(::sarmata::InitialRecognizeRequest* initial_request) {
  delete initial_request_;
  initial_request_ = initial_request;
  if (initial_request) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:sarmata.RecognizeRequest.initial_request)
}

// .sarmata.AudioRequest audio_request = 2;
inline bool RecognizeRequest::has_audio_request() const {
  return this != internal_default_instance() && audio_request_ != NULL;
}
inline void RecognizeRequest::clear_audio_request() {
  if (GetArenaNoVirtual() == NULL && audio_request_ != NULL) delete audio_request_;
  audio_request_ = NULL;
}
inline const ::sarmata::AudioRequest& RecognizeRequest::audio_request() const {
  const ::sarmata::AudioRequest* p = audio_request_;
  // @@protoc_insertion_point(field_get:sarmata.RecognizeRequest.audio_request)
  return p != NULL ? *p : *reinterpret_cast<const ::sarmata::AudioRequest*>(
      &::sarmata::_AudioRequest_default_instance_);
}
inline ::sarmata::AudioRequest* RecognizeRequest::mutable_audio_request() {
  
  if (audio_request_ == NULL) {
    audio_request_ = new ::sarmata::AudioRequest;
  }
  // @@protoc_insertion_point(field_mutable:sarmata.RecognizeRequest.audio_request)
  return audio_request_;
}
inline ::sarmata::AudioRequest* RecognizeRequest::release_audio_request() {
  // @@protoc_insertion_point(field_release:sarmata.RecognizeRequest.audio_request)
  
  ::sarmata::AudioRequest* temp = audio_request_;
  audio_request_ = NULL;
  return temp;
}
inline void RecognizeRequest::set_allocated_audio_request(::sarmata::AudioRequest* audio_request) {
  delete audio_request_;
  audio_request_ = audio_request;
  if (audio_request) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:sarmata.RecognizeRequest.audio_request)
}

// -------------------------------------------------------------------

// ConfigField

// string key = 1;
inline void ConfigField::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConfigField::key() const {
  // @@protoc_insertion_point(field_get:sarmata.ConfigField.key)
  return key_.GetNoArena();
}
inline void ConfigField::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.ConfigField.key)
}
#if LANG_CXX11
inline void ConfigField::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.ConfigField.key)
}
#endif
inline void ConfigField::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.ConfigField.key)
}
inline void ConfigField::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.ConfigField.key)
}
inline ::std::string* ConfigField::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.ConfigField.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConfigField::release_key() {
  // @@protoc_insertion_point(field_release:sarmata.ConfigField.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConfigField::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:sarmata.ConfigField.key)
}

// string value = 2;
inline void ConfigField::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConfigField::value() const {
  // @@protoc_insertion_point(field_get:sarmata.ConfigField.value)
  return value_.GetNoArena();
}
inline void ConfigField::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.ConfigField.value)
}
#if LANG_CXX11
inline void ConfigField::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.ConfigField.value)
}
#endif
inline void ConfigField::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.ConfigField.value)
}
inline void ConfigField::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.ConfigField.value)
}
inline ::std::string* ConfigField::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.ConfigField.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConfigField::release_value() {
  // @@protoc_insertion_point(field_release:sarmata.ConfigField.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConfigField::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:sarmata.ConfigField.value)
}

// -------------------------------------------------------------------

// InitialRecognizeRequest

// repeated .sarmata.ConfigField config = 1;
inline int InitialRecognizeRequest::config_size() const {
  return config_.size();
}
inline void InitialRecognizeRequest::clear_config() {
  config_.Clear();
}
inline const ::sarmata::ConfigField& InitialRecognizeRequest::config(int index) const {
  // @@protoc_insertion_point(field_get:sarmata.InitialRecognizeRequest.config)
  return config_.Get(index);
}
inline ::sarmata::ConfigField* InitialRecognizeRequest::mutable_config(int index) {
  // @@protoc_insertion_point(field_mutable:sarmata.InitialRecognizeRequest.config)
  return config_.Mutable(index);
}
inline ::sarmata::ConfigField* InitialRecognizeRequest::add_config() {
  // @@protoc_insertion_point(field_add:sarmata.InitialRecognizeRequest.config)
  return config_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::sarmata::ConfigField >*
InitialRecognizeRequest::mutable_config() {
  // @@protoc_insertion_point(field_mutable_list:sarmata.InitialRecognizeRequest.config)
  return &config_;
}
inline const ::google::protobuf::RepeatedPtrField< ::sarmata::ConfigField >&
InitialRecognizeRequest::config() const {
  // @@protoc_insertion_point(field_list:sarmata.InitialRecognizeRequest.config)
  return config_;
}

// string token = 2;
inline void InitialRecognizeRequest::clear_token() {
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& InitialRecognizeRequest::token() const {
  // @@protoc_insertion_point(field_get:sarmata.InitialRecognizeRequest.token)
  return token_.GetNoArena();
}
inline void InitialRecognizeRequest::set_token(const ::std::string& value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.InitialRecognizeRequest.token)
}
#if LANG_CXX11
inline void InitialRecognizeRequest::set_token(::std::string&& value) {
  
  token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.InitialRecognizeRequest.token)
}
#endif
inline void InitialRecognizeRequest::set_token(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.InitialRecognizeRequest.token)
}
inline void InitialRecognizeRequest::set_token(const char* value, size_t size) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.InitialRecognizeRequest.token)
}
inline ::std::string* InitialRecognizeRequest::mutable_token() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.InitialRecognizeRequest.token)
  return token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InitialRecognizeRequest::release_token() {
  // @@protoc_insertion_point(field_release:sarmata.InitialRecognizeRequest.token)
  
  return token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InitialRecognizeRequest::set_allocated_token(::std::string* token) {
  if (token != NULL) {
    
  } else {
    
  }
  token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), token);
  // @@protoc_insertion_point(field_set_allocated:sarmata.InitialRecognizeRequest.token)
}

// -------------------------------------------------------------------

// AudioRequest

// bytes content = 1;
inline void AudioRequest::clear_content() {
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AudioRequest::content() const {
  // @@protoc_insertion_point(field_get:sarmata.AudioRequest.content)
  return content_.GetNoArena();
}
inline void AudioRequest::set_content(const ::std::string& value) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.AudioRequest.content)
}
#if LANG_CXX11
inline void AudioRequest::set_content(::std::string&& value) {
  
  content_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.AudioRequest.content)
}
#endif
inline void AudioRequest::set_content(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.AudioRequest.content)
}
inline void AudioRequest::set_content(const void* value, size_t size) {
  
  content_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.AudioRequest.content)
}
inline ::std::string* AudioRequest::mutable_content() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.AudioRequest.content)
  return content_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AudioRequest::release_content() {
  // @@protoc_insertion_point(field_release:sarmata.AudioRequest.content)
  
  return content_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AudioRequest::set_allocated_content(::std::string* content) {
  if (content != NULL) {
    
  } else {
    
  }
  content_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), content);
  // @@protoc_insertion_point(field_set_allocated:sarmata.AudioRequest.content)
}

// bool end_of_stream = 2;
inline void AudioRequest::clear_end_of_stream() {
  end_of_stream_ = false;
}
inline bool AudioRequest::end_of_stream() const {
  // @@protoc_insertion_point(field_get:sarmata.AudioRequest.end_of_stream)
  return end_of_stream_;
}
inline void AudioRequest::set_end_of_stream(bool value) {
  
  end_of_stream_ = value;
  // @@protoc_insertion_point(field_set:sarmata.AudioRequest.end_of_stream)
}

// -------------------------------------------------------------------

// DefineGrammarRequest

// string token = 1;
inline void DefineGrammarRequest::clear_token() {
  token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DefineGrammarRequest::token() const {
  // @@protoc_insertion_point(field_get:sarmata.DefineGrammarRequest.token)
  return token_.GetNoArena();
}
inline void DefineGrammarRequest::set_token(const ::std::string& value) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.DefineGrammarRequest.token)
}
#if LANG_CXX11
inline void DefineGrammarRequest::set_token(::std::string&& value) {
  
  token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.DefineGrammarRequest.token)
}
#endif
inline void DefineGrammarRequest::set_token(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.DefineGrammarRequest.token)
}
inline void DefineGrammarRequest::set_token(const char* value, size_t size) {
  
  token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.DefineGrammarRequest.token)
}
inline ::std::string* DefineGrammarRequest::mutable_token() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.DefineGrammarRequest.token)
  return token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DefineGrammarRequest::release_token() {
  // @@protoc_insertion_point(field_release:sarmata.DefineGrammarRequest.token)
  
  return token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DefineGrammarRequest::set_allocated_token(::std::string* token) {
  if (token != NULL) {
    
  } else {
    
  }
  token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), token);
  // @@protoc_insertion_point(field_set_allocated:sarmata.DefineGrammarRequest.token)
}

// string name = 2;
inline void DefineGrammarRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DefineGrammarRequest::name() const {
  // @@protoc_insertion_point(field_get:sarmata.DefineGrammarRequest.name)
  return name_.GetNoArena();
}
inline void DefineGrammarRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.DefineGrammarRequest.name)
}
#if LANG_CXX11
inline void DefineGrammarRequest::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.DefineGrammarRequest.name)
}
#endif
inline void DefineGrammarRequest::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.DefineGrammarRequest.name)
}
inline void DefineGrammarRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.DefineGrammarRequest.name)
}
inline ::std::string* DefineGrammarRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.DefineGrammarRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DefineGrammarRequest::release_name() {
  // @@protoc_insertion_point(field_release:sarmata.DefineGrammarRequest.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DefineGrammarRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:sarmata.DefineGrammarRequest.name)
}

// string grammar = 3;
inline void DefineGrammarRequest::clear_grammar() {
  grammar_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DefineGrammarRequest::grammar() const {
  // @@protoc_insertion_point(field_get:sarmata.DefineGrammarRequest.grammar)
  return grammar_.GetNoArena();
}
inline void DefineGrammarRequest::set_grammar(const ::std::string& value) {
  
  grammar_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.DefineGrammarRequest.grammar)
}
#if LANG_CXX11
inline void DefineGrammarRequest::set_grammar(::std::string&& value) {
  
  grammar_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.DefineGrammarRequest.grammar)
}
#endif
inline void DefineGrammarRequest::set_grammar(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  grammar_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.DefineGrammarRequest.grammar)
}
inline void DefineGrammarRequest::set_grammar(const char* value, size_t size) {
  
  grammar_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.DefineGrammarRequest.grammar)
}
inline ::std::string* DefineGrammarRequest::mutable_grammar() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.DefineGrammarRequest.grammar)
  return grammar_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DefineGrammarRequest::release_grammar() {
  // @@protoc_insertion_point(field_release:sarmata.DefineGrammarRequest.grammar)
  
  return grammar_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DefineGrammarRequest::set_allocated_grammar(::std::string* grammar) {
  if (grammar != NULL) {
    
  } else {
    
  }
  grammar_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), grammar);
  // @@protoc_insertion_point(field_set_allocated:sarmata.DefineGrammarRequest.grammar)
}

// -------------------------------------------------------------------

// DefineGrammarResponse

// .sarmata.ResponseStatus status = 1;
inline void DefineGrammarResponse::clear_status() {
  status_ = 0;
}
inline ::sarmata::ResponseStatus DefineGrammarResponse::status() const {
  // @@protoc_insertion_point(field_get:sarmata.DefineGrammarResponse.status)
  return static_cast< ::sarmata::ResponseStatus >(status_);
}
inline void DefineGrammarResponse::set_status(::sarmata::ResponseStatus value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:sarmata.DefineGrammarResponse.status)
}

// string error = 2;
inline void DefineGrammarResponse::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DefineGrammarResponse::error() const {
  // @@protoc_insertion_point(field_get:sarmata.DefineGrammarResponse.error)
  return error_.GetNoArena();
}
inline void DefineGrammarResponse::set_error(const ::std::string& value) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.DefineGrammarResponse.error)
}
#if LANG_CXX11
inline void DefineGrammarResponse::set_error(::std::string&& value) {
  
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.DefineGrammarResponse.error)
}
#endif
inline void DefineGrammarResponse::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.DefineGrammarResponse.error)
}
inline void DefineGrammarResponse::set_error(const char* value, size_t size) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.DefineGrammarResponse.error)
}
inline ::std::string* DefineGrammarResponse::mutable_error() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.DefineGrammarResponse.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DefineGrammarResponse::release_error() {
  // @@protoc_insertion_point(field_release:sarmata.DefineGrammarResponse.error)
  
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DefineGrammarResponse::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    
  } else {
    
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:sarmata.DefineGrammarResponse.error)
}

// bool ok = 3;
inline void DefineGrammarResponse::clear_ok() {
  ok_ = false;
}
inline bool DefineGrammarResponse::ok() const {
  // @@protoc_insertion_point(field_get:sarmata.DefineGrammarResponse.ok)
  return ok_;
}
inline void DefineGrammarResponse::set_ok(bool value) {
  
  ok_ = value;
  // @@protoc_insertion_point(field_set:sarmata.DefineGrammarResponse.ok)
}

// -------------------------------------------------------------------

// RecognizeResponse

// .sarmata.ResponseStatus status = 1;
inline void RecognizeResponse::clear_status() {
  status_ = 0;
}
inline ::sarmata::ResponseStatus RecognizeResponse::status() const {
  // @@protoc_insertion_point(field_get:sarmata.RecognizeResponse.status)
  return static_cast< ::sarmata::ResponseStatus >(status_);
}
inline void RecognizeResponse::set_status(::sarmata::ResponseStatus value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:sarmata.RecognizeResponse.status)
}

// string error = 2;
inline void RecognizeResponse::clear_error() {
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RecognizeResponse::error() const {
  // @@protoc_insertion_point(field_get:sarmata.RecognizeResponse.error)
  return error_.GetNoArena();
}
inline void RecognizeResponse::set_error(const ::std::string& value) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.RecognizeResponse.error)
}
#if LANG_CXX11
inline void RecognizeResponse::set_error(::std::string&& value) {
  
  error_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.RecognizeResponse.error)
}
#endif
inline void RecognizeResponse::set_error(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.RecognizeResponse.error)
}
inline void RecognizeResponse::set_error(const char* value, size_t size) {
  
  error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.RecognizeResponse.error)
}
inline ::std::string* RecognizeResponse::mutable_error() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.RecognizeResponse.error)
  return error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RecognizeResponse::release_error() {
  // @@protoc_insertion_point(field_release:sarmata.RecognizeResponse.error)
  
  return error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RecognizeResponse::set_allocated_error(::std::string* error) {
  if (error != NULL) {
    
  } else {
    
  }
  error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), error);
  // @@protoc_insertion_point(field_set_allocated:sarmata.RecognizeResponse.error)
}

// string warning = 3;
inline void RecognizeResponse::clear_warning() {
  warning_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RecognizeResponse::warning() const {
  // @@protoc_insertion_point(field_get:sarmata.RecognizeResponse.warning)
  return warning_.GetNoArena();
}
inline void RecognizeResponse::set_warning(const ::std::string& value) {
  
  warning_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.RecognizeResponse.warning)
}
#if LANG_CXX11
inline void RecognizeResponse::set_warning(::std::string&& value) {
  
  warning_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.RecognizeResponse.warning)
}
#endif
inline void RecognizeResponse::set_warning(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  warning_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.RecognizeResponse.warning)
}
inline void RecognizeResponse::set_warning(const char* value, size_t size) {
  
  warning_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.RecognizeResponse.warning)
}
inline ::std::string* RecognizeResponse::mutable_warning() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.RecognizeResponse.warning)
  return warning_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RecognizeResponse::release_warning() {
  // @@protoc_insertion_point(field_release:sarmata.RecognizeResponse.warning)
  
  return warning_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RecognizeResponse::set_allocated_warning(::std::string* warning) {
  if (warning != NULL) {
    
  } else {
    
  }
  warning_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), warning);
  // @@protoc_insertion_point(field_set_allocated:sarmata.RecognizeResponse.warning)
}

// int32 event_time = 4;
inline void RecognizeResponse::clear_event_time() {
  event_time_ = 0;
}
inline ::google::protobuf::int32 RecognizeResponse::event_time() const {
  // @@protoc_insertion_point(field_get:sarmata.RecognizeResponse.event_time)
  return event_time_;
}
inline void RecognizeResponse::set_event_time(::google::protobuf::int32 value) {
  
  event_time_ = value;
  // @@protoc_insertion_point(field_set:sarmata.RecognizeResponse.event_time)
}

// repeated .sarmata.Phrase results = 5;
inline int RecognizeResponse::results_size() const {
  return results_.size();
}
inline void RecognizeResponse::clear_results() {
  results_.Clear();
}
inline const ::sarmata::Phrase& RecognizeResponse::results(int index) const {
  // @@protoc_insertion_point(field_get:sarmata.RecognizeResponse.results)
  return results_.Get(index);
}
inline ::sarmata::Phrase* RecognizeResponse::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:sarmata.RecognizeResponse.results)
  return results_.Mutable(index);
}
inline ::sarmata::Phrase* RecognizeResponse::add_results() {
  // @@protoc_insertion_point(field_add:sarmata.RecognizeResponse.results)
  return results_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::sarmata::Phrase >*
RecognizeResponse::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:sarmata.RecognizeResponse.results)
  return &results_;
}
inline const ::google::protobuf::RepeatedPtrField< ::sarmata::Phrase >&
RecognizeResponse::results() const {
  // @@protoc_insertion_point(field_list:sarmata.RecognizeResponse.results)
  return results_;
}

// -------------------------------------------------------------------

// Phrase_Word

// string transcript = 1;
inline void Phrase_Word::clear_transcript() {
  transcript_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Phrase_Word::transcript() const {
  // @@protoc_insertion_point(field_get:sarmata.Phrase.Word.transcript)
  return transcript_.GetNoArena();
}
inline void Phrase_Word::set_transcript(const ::std::string& value) {
  
  transcript_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.Phrase.Word.transcript)
}
#if LANG_CXX11
inline void Phrase_Word::set_transcript(::std::string&& value) {
  
  transcript_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.Phrase.Word.transcript)
}
#endif
inline void Phrase_Word::set_transcript(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  transcript_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.Phrase.Word.transcript)
}
inline void Phrase_Word::set_transcript(const char* value, size_t size) {
  
  transcript_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.Phrase.Word.transcript)
}
inline ::std::string* Phrase_Word::mutable_transcript() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.Phrase.Word.transcript)
  return transcript_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Phrase_Word::release_transcript() {
  // @@protoc_insertion_point(field_release:sarmata.Phrase.Word.transcript)
  
  return transcript_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Phrase_Word::set_allocated_transcript(::std::string* transcript) {
  if (transcript != NULL) {
    
  } else {
    
  }
  transcript_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), transcript);
  // @@protoc_insertion_point(field_set_allocated:sarmata.Phrase.Word.transcript)
}

// double confidence = 2;
inline void Phrase_Word::clear_confidence() {
  confidence_ = 0;
}
inline double Phrase_Word::confidence() const {
  // @@protoc_insertion_point(field_get:sarmata.Phrase.Word.confidence)
  return confidence_;
}
inline void Phrase_Word::set_confidence(double value) {
  
  confidence_ = value;
  // @@protoc_insertion_point(field_set:sarmata.Phrase.Word.confidence)
}

// int32 start = 3;
inline void Phrase_Word::clear_start() {
  start_ = 0;
}
inline ::google::protobuf::int32 Phrase_Word::start() const {
  // @@protoc_insertion_point(field_get:sarmata.Phrase.Word.start)
  return start_;
}
inline void Phrase_Word::set_start(::google::protobuf::int32 value) {
  
  start_ = value;
  // @@protoc_insertion_point(field_set:sarmata.Phrase.Word.start)
}

// int32 end = 4;
inline void Phrase_Word::clear_end() {
  end_ = 0;
}
inline ::google::protobuf::int32 Phrase_Word::end() const {
  // @@protoc_insertion_point(field_get:sarmata.Phrase.Word.end)
  return end_;
}
inline void Phrase_Word::set_end(::google::protobuf::int32 value) {
  
  end_ = value;
  // @@protoc_insertion_point(field_set:sarmata.Phrase.Word.end)
}

// double logprob = 5;
inline void Phrase_Word::clear_logprob() {
  logprob_ = 0;
}
inline double Phrase_Word::logprob() const {
  // @@protoc_insertion_point(field_get:sarmata.Phrase.Word.logprob)
  return logprob_;
}
inline void Phrase_Word::set_logprob(double value) {
  
  logprob_ = value;
  // @@protoc_insertion_point(field_set:sarmata.Phrase.Word.logprob)
}

// -------------------------------------------------------------------

// Phrase

// repeated .sarmata.Phrase.Word words = 1;
inline int Phrase::words_size() const {
  return words_.size();
}
inline void Phrase::clear_words() {
  words_.Clear();
}
inline const ::sarmata::Phrase_Word& Phrase::words(int index) const {
  // @@protoc_insertion_point(field_get:sarmata.Phrase.words)
  return words_.Get(index);
}
inline ::sarmata::Phrase_Word* Phrase::mutable_words(int index) {
  // @@protoc_insertion_point(field_mutable:sarmata.Phrase.words)
  return words_.Mutable(index);
}
inline ::sarmata::Phrase_Word* Phrase::add_words() {
  // @@protoc_insertion_point(field_add:sarmata.Phrase.words)
  return words_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::sarmata::Phrase_Word >*
Phrase::mutable_words() {
  // @@protoc_insertion_point(field_mutable_list:sarmata.Phrase.words)
  return &words_;
}
inline const ::google::protobuf::RepeatedPtrField< ::sarmata::Phrase_Word >&
Phrase::words() const {
  // @@protoc_insertion_point(field_list:sarmata.Phrase.words)
  return words_;
}

// double confidence = 2;
inline void Phrase::clear_confidence() {
  confidence_ = 0;
}
inline double Phrase::confidence() const {
  // @@protoc_insertion_point(field_get:sarmata.Phrase.confidence)
  return confidence_;
}
inline void Phrase::set_confidence(double value) {
  
  confidence_ = value;
  // @@protoc_insertion_point(field_set:sarmata.Phrase.confidence)
}

// bool correct = 3;
inline void Phrase::clear_correct() {
  correct_ = false;
}
inline bool Phrase::correct() const {
  // @@protoc_insertion_point(field_get:sarmata.Phrase.correct)
  return correct_;
}
inline void Phrase::set_correct(bool value) {
  
  correct_ = value;
  // @@protoc_insertion_point(field_set:sarmata.Phrase.correct)
}

// string semantic_interpretation = 4;
inline void Phrase::clear_semantic_interpretation() {
  semantic_interpretation_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Phrase::semantic_interpretation() const {
  // @@protoc_insertion_point(field_get:sarmata.Phrase.semantic_interpretation)
  return semantic_interpretation_.GetNoArena();
}
inline void Phrase::set_semantic_interpretation(const ::std::string& value) {
  
  semantic_interpretation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:sarmata.Phrase.semantic_interpretation)
}
#if LANG_CXX11
inline void Phrase::set_semantic_interpretation(::std::string&& value) {
  
  semantic_interpretation_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:sarmata.Phrase.semantic_interpretation)
}
#endif
inline void Phrase::set_semantic_interpretation(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  semantic_interpretation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:sarmata.Phrase.semantic_interpretation)
}
inline void Phrase::set_semantic_interpretation(const char* value, size_t size) {
  
  semantic_interpretation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:sarmata.Phrase.semantic_interpretation)
}
inline ::std::string* Phrase::mutable_semantic_interpretation() {
  
  // @@protoc_insertion_point(field_mutable:sarmata.Phrase.semantic_interpretation)
  return semantic_interpretation_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Phrase::release_semantic_interpretation() {
  // @@protoc_insertion_point(field_release:sarmata.Phrase.semantic_interpretation)
  
  return semantic_interpretation_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Phrase::set_allocated_semantic_interpretation(::std::string* semantic_interpretation) {
  if (semantic_interpretation != NULL) {
    
  } else {
    
  }
  semantic_interpretation_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), semantic_interpretation);
  // @@protoc_insertion_point(field_set_allocated:sarmata.Phrase.semantic_interpretation)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace sarmata

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::sarmata::ResponseStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::sarmata::ResponseStatus>() {
  return ::sarmata::ResponseStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_asr_5fservice_2eproto__INCLUDED
